#!/bin/bash
set -e

echo "Stripping leading underscores from filenames (GitHub Pages blocks these)..."
find images/fulls -type f -iname "_*.jpg" | while read -r f; do
  dir=$(dirname "$f")
  base=$(basename "$f")
  mv "$f" "$dir/${base#_}"
done

echo "Resizing images/fulls into images/thumbs (mirroring folders)..."
rm -rf images/thumbs
find images/fulls -type f -iname "*.jpg" | while read -r f; do
  rel="${f#images/fulls/}"
  dest="images/thumbs/$rel"
  mkdir -p "$(dirname "$dest")"
  magick "$f" -resize 512x512\> -quality 85 "$dest"
done

echo "Rebuilding gallery from folder structure..."
python3 << 'PYEOF'
import os, re

CAMERA_LABEL = { 'r6ii': 'Canon R6 Mark II', '7d': 'Canon 7D', 'g7x': 'PowerShot G7 X Mark II' }

entries = []
themes = set()

for cam in sorted(os.listdir('images/fulls')):
    cam_path = os.path.join('images/fulls', cam)
    if not os.path.isdir(cam_path): continue
    for theme in sorted(os.listdir(cam_path)):
        theme_path = os.path.join(cam_path, theme)
        if not os.path.isdir(theme_path): continue
        themes.add(theme)
        for fname in sorted(os.listdir(theme_path)):
            if not fname.lower().endswith('.jpg'): continue
            full = f"images/fulls/{cam}/{theme}/{fname}"
            thumb = f"images/thumbs/{cam}/{theme}/{fname}"
            label = os.path.splitext(fname)[0]
            entries.append(f"    {{ thumb: '{thumb}', full: '{full}', label: '{label}', cam: '{cam}', theme: '{theme}' }},")

with open('index.html') as fh:
    content = fh.read()

new_array = "const photos = [\n" + "\n".join(entries) + "\n  ];"
content = re.sub(r"const photos = \[.*?\];", new_array, content, flags=re.DOTALL)

theme_opts = "\n".join(f'      <option value="{t}">{t.title()}</option>' for t in sorted(themes))
content = re.sub(
    r'(<select class="theme-select" id="themeFilter">\s*<option value="all">All Themes</option>\n)(.*?)(\s*</select>)',
    lambda m: m.group(1) + theme_opts + m.group(3),
    content, flags=re.DOTALL
)

with open('index.html', 'w') as fh:
    fh.write(content)

print(f"index.html: {len(entries)} photos across {len(themes)} themes.")
PYEOF

echo "Building store-data.js from the same folder structure..."
python3 << 'PYEOF'
import os, json

CAMERA_LABEL = { 'r6ii': 'Canon R6 Mark II', '7d': 'Canon 7D', 'g7x': 'PowerShot G7 X Mark II' }

# Hand-maintained filename -> verse reference map. There's no way to detect which
# verse a photo actually shows, so this is the one place that knowledge lives.
# Anything missing or blank falls back to a generic "Verse N".
VERSE_LABELS = {}
if os.path.exists('verses.json'):
    with open('verses.json') as fh:
        VERSE_LABELS = {
            k: v for k, v in json.load(fh).items()
            if not k.startswith('_') and v.strip()
        }

photos = []
verses = []
verse_count = 0

for cam in sorted(os.listdir('images/fulls')):
    cam_path = os.path.join('images/fulls', cam)
    if not os.path.isdir(cam_path): continue
    for theme in sorted(os.listdir(cam_path)):
        theme_path = os.path.join(cam_path, theme)
        if not os.path.isdir(theme_path): continue
        for fname in sorted(os.listdir(theme_path)):
            if not fname.lower().endswith('.jpg'): continue
            full = f"images/fulls/{cam}/{theme}/{fname}"
            thumb = f"images/thumbs/{cam}/{theme}/{fname}"
            label = os.path.splitext(fname)[0]
            photos.append({
                "thumb": thumb, "full": full, "label": label,
                "cam": cam, "theme": theme
            })
            if theme.lower() == "bible":
                verse_count += 1
                verses.append({
                    "full": full,
                    "label": VERSE_LABELS.get(fname, f"Verse {verse_count}")
                })

with open('store-data.js', 'w') as fh:
    fh.write("// Auto-generated by rebuild.sh — do not hand-edit, re-run the script instead.\n")
    fh.write("const CAMERA_LABEL = " + json.dumps(CAMERA_LABEL, indent=2) + ";\n")
    fh.write("const STORE_PHOTOS = " + json.dumps(photos, indent=2) + ";\n")
    fh.write("const STORE_VERSES = " + json.dumps(verses, indent=2) + ";\n")

named = sum(1 for v in verses if not v['label'].startswith('Verse '))
print(f"store-data.js: {len(photos)} photos, {len(verses)} verse pairings ({named} named, {len(verses)-named} unnamed).")
if named < len(verses):
    print("  -> add the missing verse references in verses.json, then re-run.")
PYEOF

echo "Cleaning up loose files in images/ root..."
rm -f images/*.jpg

echo "Done."
