// Auto-generated by rebuild.sh — do not hand-edit, re-run the script instead.
const CAMERA_LABEL = {
  "r6ii": "Canon R6 Mark II",
  "7d": "Canon 7D",
  "g7x": "PowerShot G7 X Mark II"
};
const STORE_PHOTOS = [
  {
    "thumb": "images/thumbs/7d/flowers/MG_7851.jpg",
    "full": "images/fulls/7d/flowers/MG_7851.jpg",
    "label": "First Light on the Prairie",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/thumbs/7d/flowers/MG_7966-2.jpg",
    "full": "images/fulls/7d/flowers/MG_7966-2.jpg",
    "label": "Small Sun",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/thumbs/7d/flowers/MG_8060-spektrafilm-001-2.jpg",
    "full": "images/fulls/7d/flowers/MG_8060-spektrafilm-001-2.jpg",
    "label": "Crepe Myrtle, Grain",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/thumbs/7d/skies/MG_8103-2.jpg",
    "full": "images/fulls/7d/skies/MG_8103-2.jpg",
    "label": "Weather Coming In",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/7d/skies/moon-spektrafilm-001.jpg",
    "full": "images/fulls/7d/skies/moon-spektrafilm-001.jpg",
    "label": "Cold Moon",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/7d/skies/MG_8127.jpg",
    "full": "images/fulls/7d/skies/MG_8127.jpg",
    "label": "Evening Turns Over",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/7d/misc/MG_8007.jpg",
    "full": "images/fulls/7d/misc/MG_8007.jpg",
    "label": "The Quiet Chair",
    "cam": "7d",
    "theme": "misc"
  },
  {
    "thumb": "images/thumbs/g7x/skies/IMG_2590-spektrafilm-001.jpg",
    "full": "images/fulls/g7x/skies/IMG_2590-spektrafilm-001.jpg",
    "label": "Halo",
    "cam": "g7x",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/g7x/skies/IMG_2579-3.jpg",
    "full": "images/fulls/g7x/skies/IMG_2579-3.jpg",
    "label": "Blue Hour, Rising",
    "cam": "g7x",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/r6ii/flowers/799A4022-3.jpg",
    "full": "images/fulls/r6ii/flowers/799A4022-3.jpg",
    "label": "Petal Study",
    "cam": "r6ii",
    "theme": "flowers"
  },
  {
    "thumb": "images/thumbs/r6ii/flowers/799A4046.jpg",
    "full": "images/fulls/r6ii/flowers/799A4046.jpg",
    "label": "Late Bloom",
    "cam": "r6ii",
    "theme": "flowers"
  },
  {
    "thumb": "images/thumbs/r6ii/skies/799A3978.jpg",
    "full": "images/fulls/r6ii/skies/799A3978.jpg",
    "label": "Above the Treeline",
    "cam": "r6ii",
    "theme": "skies"
  },
  {
    "thumb": "images/thumbs/r6ii/bible/799A4061.jpg",
    "full": "images/fulls/r6ii/bible/799A4061.jpg",
    "label": "Open Page",
    "cam": "r6ii",
    "theme": "bible"
  },
  {
    "thumb": "images/thumbs/r6ii/bible/799A4068-2.jpg",
    "full": "images/fulls/r6ii/bible/799A4068-2.jpg",
    "label": "Marked Passage",
    "cam": "r6ii",
    "theme": "bible"
  }
];
const STORE_VERSES = [
  {
    "full": "images/fulls/r6ii/bible/799A4061.jpg",
    "label": "Verse 1"
  },
  {
    "full": "images/fulls/r6ii/bible/799A4068-2.jpg",
    "label": "Verse 2"
  }
];
