// Auto-generated by rebuild.sh — do not hand-edit, re-run the script instead.
const CAMERA_LABEL = {
  "r6ii": "Canon R6 Mark II",
  "7d": "Canon 7D",
  "g7x": "PowerShot G7 X Mark II"
};
const STORE_PHOTOS = [
  {
    "thumb": "images/print-thumbs/Beetle on a Sunflower.jpg",
    "full": "images/Prints/Beetle on a Sunflower.jpg",
    "label": "Beetle on a Sunflower",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/Crepe Myrtle in Shade.jpg",
    "full": "images/Prints/Crepe Myrtle in Shade.jpg",
    "label": "Crepe Myrtle in Shade",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/Crescent Moon in Daylight.jpg",
    "full": "images/Prints/Crescent Moon in Daylight.jpg",
    "label": "Crescent Moon in Daylight",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/print-thumbs/Lantern at Night.jpg",
    "full": "images/Prints/Lantern at Night.jpg",
    "label": "Lantern at Night",
    "cam": "7d",
    "theme": "misc"
  },
  {
    "thumb": "images/print-thumbs/Lit Cloud at Dusk.jpg",
    "full": "images/Prints/Lit Cloud at Dusk.jpg",
    "label": "Lit Cloud at Dusk",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/print-thumbs/Storm Cloud at Sunset.jpg",
    "full": "images/Prints/Storm Cloud at Sunset.jpg",
    "label": "Storm Cloud at Sunset",
    "cam": "g7x",
    "theme": "skies"
  },
  {
    "thumb": "images/print-thumbs/Sunburst Through Branches.jpg",
    "full": "images/Prints/Sunburst Through Branches.jpg",
    "label": "Sunburst Through Branches",
    "cam": "r6ii",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/Sunflower Against the Dark.jpg",
    "full": "images/Prints/Sunflower Against the Dark.jpg",
    "label": "Sunflower Against the Dark",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/Sunflower Among Leaves.jpg",
    "full": "images/Prints/Sunflower Among Leaves.jpg",
    "label": "Sunflower Among Leaves",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/White Chimney Against the Sky.jpg",
    "full": "images/Prints/White Chimney Against the Sky.jpg",
    "label": "White Chimney Against the Sky",
    "cam": "7d",
    "theme": "skies"
  },
  {
    "thumb": "images/print-thumbs/7d/flowers/Crepe Myrtle in Evening Light.jpg",
    "full": "images/Prints/7d/flowers/Crepe Myrtle in Evening Light.jpg",
    "label": "Crepe Myrtle in Evening Light",
    "cam": "7d",
    "theme": "flowers"
  },
  {
    "thumb": "images/print-thumbs/7d/skies/Treetops and Summer Clouds.jpg",
    "full": "images/Prints/7d/skies/Treetops and Summer Clouds.jpg",
    "label": "Treetops and Summer Clouds",
    "cam": "7d",
    "theme": "skies"
  }
];
const STORE_VERSES = [];
